spring:
  application:
    name: CoinSec-Backend
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.kody.coinsec.backend.common.handler
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false

sa-token:
  token-name: coinsec-token
  timeout: 604800
  active-timeout: 172800
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true